[
  {
    "name": "Amsterdam, Netherlands (Clouvider)",
    "server": "//ams.speedtest.clouvider.net/backend",
    "id": 51,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Clouvider",
    "sponsorURL": "https://www.clouvider.co.uk/"
  },
  {
    "name": "Atlanta, United States (Clouvider)",
    "server": "//atl.speedtest.clouvider.net/backend",
    "id": 53,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Clouvider",
    "sponsorURL": "https://www.clouvider.co.uk/"
  },
  {
    "name": "Bari, Italy (GARR)",
    "server": "https://st-be-ba1.infra.garr.it",
    "id": 33,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Consortium GARR",
    "sponsorURL": "//garr.it"
  },
  {
    "name": "Bologna, Italy (GARR)",
    "server": "https://st-be-bo1.infra.garr.it",
    "id": 34,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Consortium GARR",
    "sponsorURL": "//garr.it"
  },
  {
    "name": "Frankfurt, Germany (Clouvider)",
    "server": "//fra.speedtest.clouvider.net/backend",
    "id": 50,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Clouvider",
    "sponsorURL": "https://www.clouvider.co.uk/"
  },
  {
    "name": "Frankfurt, Germany 2 (DigitalOcean)",
    "server": "//speed2.lukas-heinrich.com/",
    "id": 47,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "luki9100",
    "sponsorURL": "https://lukas-heinrich.com/"
  },
  {
    "name": "Helsinki, Finland 3 (Hetzner)",
    "server": "//fi.openspeed.org/",
    "id": 22,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "B2B Risk",
    "sponsorURL": null
  },
  {
    "name": "Helsinki, Finland 5 (Hetzner)",
    "server": "//fast.kabi.tk/",
    "id": 24,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "KABI.tk",
    "sponsorURL": "//kabi.tk"
  },
  {
    "name": "Indianapolis, United States ",
    "server": "https://speedtest.chet.space/",
    "id": 55,
    "dlURL": "backend/garbage.php",
    "ulURL": "backend/empty.php",
    "pingURL": "backend/empty.php",
    "getIpURL": "backend/getIP.php",
    "sponsorName": "Erda-Networks.com",
    "sponsorURL": "http://blog.chet.space"
  },
  {
    "name": "Las Vegas, United States (BuyVM)",
    "server": "https://lv1.backend.librespeed.nixnet.services/",
    "id": 37,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "NixNet",
    "sponsorURL": "https://nixnet.services"
  },
  {
    "name": "London, England (Clouvider)",
    "server": "//lon.speedtest.clouvider.net/backend",
    "id": 49,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Clouvider",
    "sponsorURL": "https://www.clouvider.co.uk/"
  },
  {
    "name": "Los Angeles, United States (Clouvider)",
    "server": "//la.speedtest.clouvider.net/backend",
    "id": 54,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Clouvider",
    "sponsorURL": "https://www.clouvider.co.uk/"
  },
  {
    "name": "New York, United States (BuyVM)",
    "server": "https://ny1.backend.librespeed.nixnet.services/",
    "id": 38,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "NixNet",
    "sponsorURL": "https://nixnet.services"
  },
  {
    "name": "New York, United States (Clouvider)",
    "server": "//nyc.speedtest.clouvider.net/backend",
    "id": 52,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Clouvider",
    "sponsorURL": "https://www.clouvider.co.uk/"
  },
  {
    "name": "Nottingham, England (LayerIP)",
    "server": "https://uk1.backend.librespeed.org",
    "id": 43,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "fosshost.org",
    "sponsorURL": "https://fosshost.org"
  },
  {
    "name": "Nuremberg, Germany 2 (Netcup)",
    "server": "//de2.backend.librespeed.org",
    "id": 29,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "NixNet",
    "sponsorURL": "https://nixnet.services"
  },
  {
    "name": "Nuremberg, Germany 5 (Hetzner)",
    "server": "https://speedtest.ciapa.tech/",
    "id": 32,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": null,
    "sponsorURL": null
  },
  {
    "name": "Nuremberg, Germany 6 (Hetzner)",
    "server": "//librespeed.lukas-heinrich.com/",
    "id": 46,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "luki9100",
    "sponsorURL": "https://lukas-heinrich.com/"
  },
  {
    "name": "Paris, France 2 (online.net)",
    "server": "https://muchspeed.network",
    "id": 57,
    "dlURL": "backend/garbage.php",
    "ulURL": "backend/empty.php",
    "pingURL": "backend/empty.php",
    "getIpURL": "backend/getIP.php",
    "sponsorName": "Linuxxx",
    "sponsorURL": null
  },
  {
    "name": "Roma, Italy (GARR)",
    "server": "https://st-be-rm2.infra.garr.it",
    "id": 35,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Consortium GARR",
    "sponsorURL": "//garr.it"
  },
  {
    "name": "Roost, Luxembourg (BuyVM)",
    "server": "https://lux1.backend.librespeed.nixnet.services/",
    "id": 39,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "NixNet",
    "sponsorURL": "https://nixnet.services"
  },
  {
    "name": "Strasbourg, France (Host Europe)",
    "server": "https://sxb.bandspeed.de/",
    "id": 44,
    "dlURL": "backend/garbage.php",
    "ulURL": "backend/empty.php",
    "pingURL": "backend/empty.php",
    "getIpURL": "backend/getIP.php",
    "sponsorName": "adminForge",
    "sponsorURL": "https://adminforge.de/"
  },
  {
    "name": "Sydney, Australia (Linode)",
    "server": "//librespeed.fossdaily.xyz",
    "id": 36,
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "Foss Daily",
    "sponsorURL": "https://fossdaily.xyz/"
  },
  {
      "name":"Istanbul, Türkiye, Turkey (GuzelHosting)",
      "server":"\/\/alicangonullu.info/lisans/speedtest\/",
      "id":1,
      "dlURL":"garbage.php",
      "ulURL":"empty.php",
      "pingURL":"empty.php",
      "getIpURL":"getIP.php",
      "sponsorName":"AliCanGonullu",
      "sponsorURL":"https:\/\/www.alicangonullu.info\/"
   },
   {
      "name":"Frankfurt, Germany (Clouvider)",
      "server":"\/\/fra.speedtest.clouvider.net\/backend",
      "id":2,
      "dlURL":"garbage.php",
      "ulURL":"empty.php",
      "pingURL":"empty.php",
      "getIpURL":"getIP.php",
      "sponsorName":"Clouvider",
      "sponsorURL":"https:\/\/www.clouvider.co.uk\/"
   },
      {
      "name":"AliSpeed, US (000webhost)",
      "server":"\/\/alispeed1.000webhostapp.com\/",
      "id":3,
      "dlURL":"garbage.php",
      "ulURL":"empty.php",
      "pingURL":"empty.php",
      "getIpURL":"getIP.php",
      "sponsorName":"000webhost",
      "sponsorURL":"https:\/\/000webhost.com\/"
   }
]
